DataAcquire/urls.py
import xadmin
from django.contrib import admin
from django.urls import re_path,include
from django.views.generic import TemplateView
from users.views import LoginView,RegisterView,ActiveUserView,ForgetPwdView,ResetView,ModifyPwdView,PcDataView,PcDataMouseView,MoboileDataView,logout_view
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
# from django.contrib.auth.views import logout
from auth_server.views import register_keystroke

xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
from xadmin.plugins import xversion
xversion.register_models()

urlpatterns = [
    # re_path('^xadmin/', xadmin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    re_path(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    re_path(r'^register/', RegisterView.as_view(), name='register'),
    re_path(r'^login/', LoginView.as_view(), name='login'),
    re_path(r'^captcha/', include('captcha.urls')),
    re_path(r'^forget/$', ForgetPwdView.as_view(), name='forget'),
    # url(r'^logout/$', logout_view, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^logout/$', auth_views.LogoutView.as_view(),{'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^pc_data_keystroke/$',PcDataView.as_view(),name='pc_data'),
    url(r'^pc_data_mouse/$',PcDataMouseView.as_view(),name='pc_data_mouse'),
    url(r'mobile_data',MoboileDataView.as_view(),name='mobile_data'),

    url(r'^server/register_keystroke/$',register_keystroke,name='register_keystroke')
]

apps/users/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/3/6 19:24

from django import forms
from captcha.fields import CaptchaField


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5)

class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)#,error_messages={'invalid':'请输入一个有效的邮箱地址'})
    password = forms.CharField(required=True,min_length=5,error_messages={'invalid':'密码至少6个字符','required':'请输入密码'})
    age = forms.IntegerField(required=True,error_messages={'invalid':'请输入正确的年龄','required':'请输入年龄'})
    gender = forms.CharField(required=True,max_length=10,error_messages={'invalid':'请输入性别'})
    captcha = CaptchaField(error_messages={'required': '验证码错误'})

class PcFrom(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5)

class ForgetPwdForm(forms.Form):
    # username = forms.EmailField(required=True,error_messages={'required':'账号输入有误'})
    email = forms.EmailField(required=True)#,error_messages={'invalid':'请输入一个有效的邮箱地址'})
    captcha = CaptchaField(error_messages={'required': '验证码错误'})

class ResetPwdForm(forms.Form):
    password1 = forms.CharField(required=True)
    password2 = forms.CharField(required=True)

templates/forgetpwd.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>慕学网首页</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
</head>
<body>
<!--提示弹出框-->
<div class="successbox dialogbox" id="jsSuccessTips">
    <h1>成功提交</h1>
    <div class="close jsCloseDialog"><img src="/static/pics/dig_close.png"/></div>
    <div class="cont">
        <h2>您的需求提交成功！</h2>
        <p></p>
    </div>
</div>
<div class="resetpassbox dialogbox" id="jsSetNewPwd">
    <h1>重新设置密码</h1>
    <div class="close jsCloseDialog"><img src="/static/pics/dig_close.png"/></div>
    <p class="green">请输入新密码</p>
    <form id="jsSetNewPwdForm">
        <div class="box">
            <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
            <input type="password" name="password" id="jsResetPwd" placeholder="请输入新密码"/>
        </div>
        <div class="box">
            <span class="word2">确&nbsp;认&nbsp;密&nbsp;码</span>
            <input type="password" name="password2" id="jsResetPwd2" placeholder="请再次输入新密码"/>
        </div>
        <div class="box">
            <span class="word2">验&nbsp;&nbsp;证&nbsp;&nbsp;码</span>
            <input type="text" name="code" id="jsResetCode" placeholder="请输入手机验证码"/>
        </div>
        <div class="error btns" id="jsSetNewPwdTips"></div>
        <div class="button">
            <input type="hidden" name="mobile" id="jsInpResetMobil"/>
            <input id="jsSetNewPwdBtn" type="button" value="提交"/>
        </div>
        <input type='hidden' name='csrfmiddlewaretoken' value='mymQDzHWl2REXIfPMg2mJaLqDfaS1sD5'/>
    </form>
</div>
<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li><a href="login.html">[登录]</a></li>
                <li class="active"><a href="/forgetpwd/">[忘记密码]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>忘记密码</h1>
                <a class="index-font" href="index.html">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                        <li><a href=""><img width="483" height="472" src="/static/pics/banner1.jpg"/></a>
                        </li>
                        <li><a href=""><img width="483" height="472" src="/static/pics/banner1.jpg"/></a>
                        </li>
                        <li><a href=""><img width="483" height="472" src="/static/pics/banner1.jpg"/></a>
                        </li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>忘记密码</h2>
                <form id="jsFindPwdForm" method="post" action="{% url 'forget' %}" autocomplete="off">
                    {#                    <input type='hidden' name='csrfmiddlewaretoken' value='mymQDzHWl2REXIfPMg2mJaLqDfaS1sD5' />#}
                    <div class="form-group marb20 {% if forget_pwd_form.email.errors %}errorput{% endif %}">
                        <label>帐&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</label>
                        <input type="text" id="account" name="email" value="{{ forget_pwd_form.email.value }}" placeholder="邮箱"/>
                    </div>
                    <div class="form-group captcha1 marb38 {% if forget_pwd_form.captcha.errors %}errorput{% endif %}">
                        <label>验&nbsp;证&nbsp;码</label>
                        {{ forget_pwd_form.captcha }}
                        {#                        <img src="/captcha/image/997454dc58799e806f18d21eac296581a8c6ef02/" alt="captcha" class="captcha" /> <input id="id_captcha_0" name="captcha_0" type="hidden" value="997454dc58799e806f18d21eac296581a8c6ef02" /> <input autocomplete="off" id="id_captcha_1" name="captcha_1" type="text" />#}
                    </div>
                    <div class="error btns" id="jsForgetTips">
                        {% for key,value in forget_pwd_form.errors.items %}
                            {{ value }}
                        {% endfor %}
                        {{ msg }}
                    </div>
                    <input type="hidden" name="sms_type" value="1">
                    <input class="btn btn-green" id="jsFindPwdBtn" type="submit" value="提交"/>
                    <p class="form-p" style="bottom:40px;">您还可以<a href="l{% url 'login' %}"> [直接登录]</a></p>
                    {#                <input type='hidden' name='csrfmiddlewaretoken' value='5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy' />#}
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/validateDialog.js" type="text/javascript"></script>
<script src="/static/js/login.js" type="text/javascript"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<head>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-theme.css">
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/index.css">
</head>


<body class="window">
{% if request.user.is_authenticated %}
    <div class="container header">
        <img class="school_logo" src="../static/pics/school_logo.png">
        <dl class="fr">
            {#                <img class="down fr" src="/static/pics/top_down.png"/></dd>#}
        </dl>

        <div class="bottom fr">
            <dt>
            <dd style="color: #0f0f0f">{{ request.session.username }}
                <img width="20" height="20" src="/static/pics/default_big_14.png"/>
                <a class="fr" href="/logout/">退出</a>
            </dt>

        </div>
        <!--登录后跳转-->
        {#        <a class="fr registerbtn" href="{% url 'register' %}">注册</a>#}
        {#        <a class="fr loginbtn" href="{% url 'login' %}">登录</a>#}
    </div>

{% else %}
    <div class="container header">
        <img class="school_logo" src="../static/pics/school_logo.png">
    </div>
    <div class="container header">
        <!--登录后跳转-->
        <a class="fr registerbtn" href="{% url 'register' %}">注册</a>
        <a class="fr loginbtn" href="{% url 'login' %}">登录</a>
    </div>
{% endif %}

<section class="jumbotron full-width full-height"
         data-pages-bg-image="https://d1f4mcvm39v27z.cloudfront.net/images/rallyhrwebheroimage-4.jpg"
         data-pages="parallax"
         style="background-image: url(../static/pics/background.jpg); background-position: center 50%; background-size: cover;">
    <div class="full-height" style="margin-top: 100px">
        <div class="page-header">
            <h3 style="text-align:center">智能网络与网络安全教育部重点实验室</h3>
            <h1 class="modal-title">人机交互数据采集平台</h1>
        </div>

        <div class="bottom-containner container">
            <button type="button" onclick="newwin_pc()" class="btn-font1 btn btn-default" id="but1" href="{% url 'pc_data' %}">电脑端击键数据采集</button>
        </div>

        <div class="bottom-containner container">
            <a type="button" class="btn-font2 btn btn-default" id="but2" onclick="newwin_mobile()">手机sensor数据采集</a>
        </div>
    </div>
</section>
<script>
    var but1 = document.getElementById('but1');
    var but2 = document.getElementById('but2');

    function newwin_pc() {
        if('{{ request.user.is_authenticated }}' === 'True'){
            window.open("{% url 'pc_data' %}");
        }
        else {
            alert('请先登录');
        }
    }
    function newwin_mobile() {
        if('{{ request.user.is_authenticated }}' === 'True'){
            window.open("{% url 'mobile_data' %}");
        }
        else {
            alert('请先登录');
        }
    }
</script>
</body>
</html>

templates/jjj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
a img{border:none} .testdiv *{ vertical-align:middle; }
</style>
    <title>Title</title>
</head>
<body>

<div class="testdiv">
    <a href="http://www.zc144.com/">
    <img src="http://www.zc144.com/download/Template.jpg" alt="这里是图片"/>
    </a>
    <span>这里是文字,看看文字对齐了没</span>
</div>
</body>
</html>

templates/mobile_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta charset="UTF-8">
    <title>移动端数据采集</title>
<link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/mobile.css">
    <script src="/static/js/jquery.min.js"></script>

</head>
<body>
<header>
{% if request.user.is_authenticated %}
    <div class="border-top container-fluid">
        <img class="school_logo" src="../static/pics/school_logo.png">
        <div class="bottom fr" id="fr_div">
            <a class="fl mar10_font" id="username_a">{{ request.session.username }}</a>
            <img id="head_image" width="20" height="20" src="../static/pics/default_big_14.png"/>
            <a class="fr mar10_font" id="logout_a" href="/logout/">退出</a>
        </div>
        <!--登录后跳转-->
        {#        <a class="fr registerbtn" href="{% url 'register' %}">注册</a>#}
        {#        <a class="fr loginbtn" href="{% url 'login' %}">登录</a>#}
    </div>

{% else %}
    <div class="container-fluid border-top">
        <img class="school_logo" src="../static/pics/school_logo.png">
        <!--登录后跳转-->
        <a class="fr btn btn-outline-secondary mybtn_top" href="{% url 'register' %}">注册</a>
        <a class="fr btn btn-secondary mybtn_top" href="{% url 'login' %}">登录</a>
    </div>
{% endif %}
</header>

<div class="container">

</div>

<script src="/static/js/mobile.js"></script>
<script src="/static/js/bootstrap.js"></script>
<script src="/static/js/carousel-swipe.js"></script>

</body>
</html>

templates/pc_data_mouse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>西安交通大学人机交互数据采集平台</title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css/pc_data_mouse.css">

</head>
<body>
{% if request.user.is_authenticated %}
    <div class="border-top container-fluid">
        <img class="school_logo" src="../static/pics/school_logo.png">
        <div class="bottom fr" id="fr">
            <a class="fl mar10_font" id="username_a">{{ request.session.username }}</a>
            <img id="head_image" width="20" height="20" src="../static/pics/default_big_14.png"/>
            <a class="fr mar10_font" id="logout_a" href="/logout/">退出</a>
        </div>
        <!--登录后跳转-->
        {#        <a class="fr registerbtn" href="{% url 'register' %}">注册</a>#}
        {#        <a class="fr loginbtn" href="{% url 'login' %}">登录</a>#}
    </div>

{% else %}
    <div class="container-fluid border-top">
        <img class="school_logo" src="../static/pics/school_logo.png">
        <!--登录后跳转-->
        <a class="fr btn btn-outline-secondary mybtn_top" href="{% url 'register' %}">注册</a>
        <a class="fr btn btn-secondary mybtn_top" href="{% url 'login' %}">登录</a>
    </div>
{% endif %}


<script src="../static/js/pc_data_mouse.js"></script>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>西安交大人机交互数据采集平台注册</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">

</head>
<body>
<div class="loginbox dialogbox">
    <h1>账号登录</h1>
    <div class="close jsCloseDialog"><img src="/static/pics/dig_close.png"/></div>
    <div class="cont">
        <form id="jsLoginForm" autocomplete="off">
            <div class="box">
                <span class="word3">用户名</span>
                <input type="text" name="account_l" id="account_l" placeholder="手机号/邮箱"/>
            </div>
            <div class="box">
                <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
                <input type="password" name="password_l" id="password_l" placeholder="请输入您的密码"/>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips">
            </div> <!--登录错误提示-->
            <div class="btns">
                <span><input type="checkbox" id="jsAutoLogin"/>&nbsp;自动登录</span>
                <span class="forget btn fr">忘记密码</span>
            </div>
            <div class="button">
                <input type="button" value="登录" id="jsLoginBtn"/>
            </div>
            <div class="btns">
                <span class="fr">没有账号？<span class="regist btn">立即注册</span></span>
            </div>
        </form>
    </div>
</div>
<div class="dialog" id="jsDialog">
    <!--提示弹出框-->
    <div class="successbox dialogbox" id="jsSuccessTips">
        <h1>成功提交</h1>
        <div class="close jsCloseDialog"><img src="/static/pics/dig_close.png"/></div>
        <div class="cont">
            <h2>您的需求提交成功！</h2>
            <p></p>
        </div>
    </div>
    <div class="noactivebox dialogbox" id="jsUnactiveForm">
        <h1>邮件验证提示</h1>
        <div class="close jsCloseDialog"><img src="/static/pics/dig_close.png"/></div>
        <div class="center">
            <img src="/static/pics/send.png"/>
            <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
            <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
            <p class="zy_success upmove"></p>
            <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>
            <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin"
                                                                 style="cursor: pointer;">再次发送验证邮件</span></p>
        </div>
    </div>
</div>

<div class="bg" id="dialogBg"></div>
{#<header>#}
{#    <div class="c-box fff-box">#}
{#        <div class="wp header-box">#}
{#            <p class="fl hd-tips">西安交大数据采集平台</p>#}
{#            <ul class="fr hd-bar">#}
{#                <li><a href="login.html">[登录]</a></li>#}
{#                <li class="active"><a href="register.html">[注册]</a></li>#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{#</header>#}
<div class="c-box bg-box">
    <div class="branding">
    </div>
    <div class="login-box">
        <h1>用户注册</h1>
        <div id="back_to_index">
            <a class="index-logo" href="{% url 'index' %}"></a>
            <a class="index-font" href="{% url 'index' %}">回到首页</a>
        </div>
        <div class="center_div form-box">
            <div id="tab_register">
                <!--<h2 class="active">手机注册</h2>-->
                <h2>邮箱注册</h2>
            </div>

            <!--<div class="tab-form">-->
            <!--<form id="mobile_register_form" autocomplete="off">-->
            <!--<input type='hidden' name='csrfmiddlewaretoken' value='gTZljXgnpvxn0fKZ1XkWrM1PrCGSjiCZ' />-->
            <!--<div class="form-group marb20">-->
            <!--<label>手&nbsp;机&nbsp;号</label>-->
            <!--<input id="jsRegMobile" name="account" type="text" placeholder="请输入您的手机号码" />-->
            <!--</div>-->
            <!--<div class="form-group marb20" id="jsRefreshCode">-->
            <!--<label>验&nbsp;证&nbsp;码</label>-->
            <!--<input autocomplete="off" class="form-control-captcha mobile-register-captcha" id="mobile-register-captcha_1" name="captcha_m_1" placeholder="请输入验证码" type="text" /> <input class="form-control-captcha mobile-register-captcha" id="mobile-register-captcha_0" name="captcha_m_0" placeholder="请输入验证码" type="hidden" value="29953bacf7005e8469388b449d97d00d523c1706" /> &nbsp;<img src="/captcha/image/29953bacf7005e8469388b449d97d00d523c1706/" alt="captcha" class="captcha" />-->
            <!--</div>-->
            <!--<div class="clearfix">-->
            <!--<div class="form-group marb8 verify-code">-->
            <!--<label>短信验证码</label>-->
            <!--<input id="jsPhoneRegCaptcha" name="mobile_code" type="text" placeholder="输入手机验证码" />-->
            <!--</div>-->
            <!--<input class="verify-code-btn sendcode" id="jsSendCode" value="发送验证码">-->
            <!--</div>-->
            <!--<div class="form-group marb8">-->
            <!--<label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>-->
            <!--<input id="jsPhoneRegPwd" name="password_m" type="password" placeholder="请输入6-20位非中文字符密码" />-->
            <!--</div>-->
            <!--<div class="error btns" id="jsMobileTips"></div>-->
            <!--<div class="auto-box marb8">-->

            <!--</div>-->
            <!--<input class="btn btn-green" id="jsMobileRegBtn" type="button" value="注册并登录" />-->
            <!--</form>-->
            <!--</div>-->
            {% if register_form.email.value %}
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="{% url 'register' %}" autocomplete="off">
                        <input type='hidden' name='csrfmiddlewaretoken' value='gTZljXgnpvxn0fKZ1XkWrM1PrCGSjiCZ'/>
                        <div class="form-group marb8 {% if register_form.email.errors %}errorput{% endif %}">
                            <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                            <input type="text" id="id_email" name="email" value="{{ register_form.email.value }}"
                                   placeholder="请输入您的邮箱"/>
                        </div>
                        <div class="form-group marb8 {% if register_form.errors.password %}errorput{% endif %}">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"
                                   value="{{ register_form.password.value }}"
                                   placeholder="请输入6-20位非中文字符密码"/>
                        </div>
                        <div class="form-group marb8 {% if register_form.errors.age %}errorput{% endif %}">
                            <label>年&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;龄</label>
                            <input type="text" id="id_age" name="age"
                                   value="{{ register_form.age.value }}"
                                   placeholder="请输入年龄"/>
                        </div>
                        <div class="form-group marb20 {% if register_form.errors.gender %}errorput{% endif %}">
                            <label>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别</label>
                            <input type="text" id="id_gender" name="gender"
                                   value="{{ register_form.gender.value }}"
                                   placeholder="请输入性别"/>
                        </div>
                        <div class="form-group marb8 captcha1 {% if register_form.errors.password %}errorput{% endif %}">
                            <label>验&nbsp;证&nbsp;码</label>
                            {{ register_form.captcha }}
                        </div>
                        <div class="error btns" id="jsEmailTips">
                            {% for key,value in register_form.errors.items %}
                                {{ value }}
                            {% endfor %}
                            {{ msg }}
                        </div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录"/>
                        {#                        <input type='hidden' name='csrfmiddlewaretoken' value='5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy'/>#}
                        {% csrf_token %}
                    </form>
                </div>
            {% else %}
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="{% url 'register' %}" autocomplete="off">
                        <input type="password" style="display:none;" name="hack">

                        <div class="form-group marb8 {% if register_form.email.errors %}errorput{% endif %}">
                            <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                            <input type="text" id="id_email" name="email" placeholder="请输入您的邮箱" autocomplete="off"/>
                        </div>
                        <div class="form-group marb8 {% if register_form.errors.password %}errorput{% endif %}">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password" autocomplete="new-password"
                                   placeholder="请输入6-20位非中文字符密码"/>
                        </div>
                        <div class="form-group marb8 {% if register_form.errors.age %}errorput{% endif %}">
                            <label>年&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;龄</label>
                            <input type="text" id="id_age" name="age"
                                   placeholder="请输入年龄"/>
                        </div>
                        <div class="form-group marb20 {% if register_form.errors.gender %}errorput{% endif %}">
                            <label>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别</label>
                            <input type="text" id="id_gender" name="gender"
                                   placeholder="请输入性别"/>
                        </div>
                        <div class="form-group marb8 captcha1 {% if register_form.errors.password %}errorput{% endif %}">
                            <label>验&nbsp;证&nbsp;码</label>
                            {{ register_form.captcha }}
                        </div>
                        <div class="error btns" id="jsEmailTips">
                            {% for key,value in register_form.errors.items %}
                                {{ value }}
                            {% endfor %}
                            {{ msg }}
                        </div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录"/>
                        {#                        <input type='hidden' name='csrfmiddlewaretoken' value='5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy'/>#}
                        {% csrf_token %}
                    </form>
                </div>
            {% endif %}
            <p class="form-p">已有账号？<a href="/login/">[立即登录]</a></p>
        </div>
    </div>
    <input id="isLogin" type="hidden" value="False"/>
    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/js/unslider.js" type="text/javascript"></script>
    <script src="/static/js/validateDialog.js" type="text/javascript"></script>
    <script src="/static/js/login.js" type="text/javascript"></script>
</body>
</html>